"""Train and export Sentinel's dependency-free linear shadow classifier.

The TypeScript feature contract is the source of truth. This script consumes the
JSONL generated by ``npm run export:dataset`` and exports plain coefficients and
a bias; inference in the SDK only needs a dot product and a sigmoid.

Metrics are out-of-fold. The final exported model is then fitted on all rows, so
its in-sample predictions must never be presented as evaluation metrics.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedGroupKFold, StratifiedKFold, cross_val_predict


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATASET = ROOT / "typescript" / "benchmark" / "dataset.jsonl"
DEFAULT_MODEL = ROOT / "typescript" / "src" / "analyzer" / "shadow-model-v1.json"
DEFAULT_REPORT = ROOT / "typescript" / "benchmark" / "shadow-training-report.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--model-out", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--report-out", type=Path, default=DEFAULT_REPORT)
    return parser.parse_args()


def load_dataset(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    lines = [line for line in path.read_text(encoding="utf-8").splitlines() if line]
    if len(lines) < 2:
        raise ValueError(f"Dataset has no rows: {path}")
    header = json.loads(lines[0])
    rows = [json.loads(line) for line in lines[1:]]
    width = len(header["names"])
    for row in rows:
        if len(row["values"]) != width:
            raise ValueError(f"Row {row['id']} has {len(row['values'])} values; expected {width}")
    return header, rows


def new_model() -> LogisticRegression:
    # Features are already bounded to [0, 1], so no runtime scaler is needed.
    return LogisticRegression(
        C=1.0,
        class_weight="balanced",
        max_iter=2_000,
        random_state=42,
        solver="liblinear",
    )


def metric_block(labels: np.ndarray, probabilities: np.ndarray) -> dict[str, Any]:
    predictions = (probabilities >= 0.5).astype(int)
    tn, fp, fn, tp = confusion_matrix(labels, predictions, labels=[0, 1]).ravel()
    return {
        "precision": float(precision_score(labels, predictions, zero_division=0)),
        "recall": float(recall_score(labels, predictions, zero_division=0)),
        "f1": float(f1_score(labels, predictions, zero_division=0)),
        "accuracy": float(accuracy_score(labels, predictions)),
        "rocAuc": float(roc_auc_score(labels, probabilities)),
        "confusion": {"trueNegative": int(tn), "falsePositive": int(fp), "falseNegative": int(fn), "truePositive": int(tp)},
    }


def out_of_fold(
    features: np.ndarray,
    labels: np.ndarray,
    groups: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    stratified = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    stratified_probabilities = cross_val_predict(
        new_model(), features, labels, cv=stratified, method="predict_proba"
    )[:, 1]

    # This stricter view keeps scenario families together. It is noisier with
    # only 16 groups, but better exposes whether the model generalizes beyond
    # close variants of a conversation pattern.
    grouped = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
    grouped_probabilities = cross_val_predict(
        new_model(), features, labels, groups=groups, cv=grouped, method="predict_proba"
    )[:, 1]
    return stratified_probabilities, grouped_probabilities


def main() -> None:
    args = parse_args()
    header, rows = load_dataset(args.dataset)
    features = np.asarray([row["values"] for row in rows], dtype=float)
    labels = np.asarray([row["label"] for row in rows], dtype=int)
    groups = np.asarray([row["group"] for row in rows])

    stratified_probabilities, grouped_probabilities = out_of_fold(features, labels, groups)

    final_model = new_model()
    final_model.fit(features, labels)
    coefficients = final_model.coef_[0]
    bias = float(final_model.intercept_[0])

    model_payload = {
        "kind": "logistic_regression",
        "schemaVersion": int(header["schemaVersion"]),
        "featureNames": header["names"],
        "coefficients": [float(value) for value in coefficients],
        "bias": bias,
        "threshold": 0.5,
        "trainedRows": len(rows),
        "trainingNote": "Fitted on the complete small benchmark corpus for shadow-only inference; use cross-validation report for evaluation.",
    }
    report_payload = {
        "dataset": str(args.dataset.relative_to(ROOT)),
        "schemaVersion": int(header["schemaVersion"]),
        "rows": len(rows),
        "classCounts": {
            "benign": int((labels == 0).sum()),
            "risk": int((labels == 1).sum()),
        },
        "threshold": 0.5,
        "crossValidation": {
            "stratified5Fold": metric_block(labels, stratified_probabilities),
            "stratifiedGroup5Fold": metric_block(labels, grouped_probabilities),
        },
        "cases": [
            {
                "id": row["id"],
                "group": row["group"],
                "label": row["label"],
                "stratifiedOofProbability": float(stratified_probabilities[index]),
                "groupedOofProbability": float(grouped_probabilities[index]),
            }
            for index, row in enumerate(rows)
        ],
        "limitations": [
            "Only 135 labeled conversations are available.",
            "Rows come from a curated benchmark rather than independent production traffic.",
            "The exported full-data model is for shadow measurement, not decision-making.",
        ],
    }

    args.model_out.parent.mkdir(parents=True, exist_ok=True)
    args.report_out.parent.mkdir(parents=True, exist_ok=True)
    args.model_out.write_text(json.dumps(model_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.report_out.write_text(json.dumps(report_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(json.dumps(report_payload["crossValidation"], indent=2))
    print(f"Exported model to {args.model_out}")


if __name__ == "__main__":
    main()
