"""Train and export Sentinel's dependency-free linear shadow classifier.

The TypeScript feature contract is the source of truth. This script consumes the
JSONL generated by ``npm run export:dataset`` and exports plain coefficients and
a bias; inference in the SDK only needs a dot product and a sigmoid.

Metrics are out-of-fold. The final exported model is then fitted on all rows, so
its in-sample predictions must never be presented as evaluation metrics.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedGroupKFold, StratifiedKFold, cross_val_predict


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATASET = ROOT / "typescript" / "benchmark" / "dataset.jsonl"
DEFAULT_CORPUS = ROOT / "typescript" / "benchmark" / "corpus.json"
DEFAULT_BENCHMARK = ROOT / "typescript" / "benchmark" / "reviewed-report.json"
DEFAULT_MODEL = ROOT / "typescript" / "src" / "analyzer" / "shadow-model-v2.json"
DEFAULT_REPORT = ROOT / "typescript" / "benchmark" / "shadow-training-report.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument("--benchmark", type=Path, default=DEFAULT_BENCHMARK)
    parser.add_argument("--model-out", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--report-out", type=Path, default=DEFAULT_REPORT)
    parser.add_argument(
        "--include-unreviewed",
        action="store_true",
        help="Research only: include labels that have not passed the corpus review gate.",
    )
    return parser.parse_args()


def load_dataset(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    lines = [line for line in path.read_text(encoding="utf-8").splitlines() if line]
    if len(lines) < 2:
        raise ValueError(f"Dataset has no rows: {path}")
    header = json.loads(lines[0])
    rows = [json.loads(line) for line in lines[1:]]
    width = len(header["names"])
    for row in rows:
        if len(row["values"]) != width:
            raise ValueError(f"Row {row['id']} has {len(row['values'])} values; expected {width}")
    return header, rows


def new_model() -> LogisticRegression:
    # Features are already bounded to [0, 1], so no runtime scaler is needed.
    return LogisticRegression(
        C=1.0,
        class_weight="balanced",
        max_iter=2_000,
        random_state=42,
        solver="liblinear",
    )


def bootstrap_interval(
    labels: np.ndarray,
    probabilities: np.ndarray,
    metric: str,
    *,
    threshold: float = 0.5,
    samples: int = 2_000,
) -> list[float]:
    """Non-parametric 95% interval over the fixed out-of-fold predictions."""
    rng = np.random.default_rng(42)
    values: list[float] = []
    predictions = (probabilities >= threshold).astype(int)
    for _ in range(samples):
        indices = rng.integers(0, len(labels), len(labels))
        y = labels[indices]
        p = probabilities[indices]
        predicted = predictions[indices]
        if metric == "precision":
            value = precision_score(y, predicted, zero_division=0)
        elif metric == "recall":
            value = recall_score(y, predicted, zero_division=0)
        elif metric == "f1":
            value = f1_score(y, predicted, zero_division=0)
        elif metric == "accuracy":
            value = accuracy_score(y, predicted)
        elif metric == "rocAuc":
            if len(np.unique(y)) < 2:
                continue
            value = roc_auc_score(y, p)
        else:
            raise ValueError(f"Unknown bootstrap metric: {metric}")
        values.append(float(value))
    if not values:
        return [0.0, 0.0]
    return [float(np.quantile(values, 0.025)), float(np.quantile(values, 0.975))]


def metric_block(
    labels: np.ndarray,
    probabilities: np.ndarray,
    *,
    threshold: float = 0.5,
    with_intervals: bool = True,
) -> dict[str, Any]:
    predictions = (probabilities >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(labels, predictions, labels=[0, 1]).ravel()
    has_both_classes = len(np.unique(labels)) == 2
    result: dict[str, Any] = {
        "precision": float(precision_score(labels, predictions, zero_division=0)),
        "recall": float(recall_score(labels, predictions, zero_division=0)),
        "f1": float(f1_score(labels, predictions, zero_division=0)),
        "accuracy": float(accuracy_score(labels, predictions)),
        "rocAuc": float(roc_auc_score(labels, probabilities)) if has_both_classes else None,
        "confusion": {"trueNegative": int(tn), "falsePositive": int(fp), "falseNegative": int(fn), "truePositive": int(tp)},
    }
    if with_intervals:
        result["bootstrap95"] = {
            name: bootstrap_interval(labels, probabilities, name, threshold=threshold)
            for name in ("precision", "recall", "f1", "accuracy", "rocAuc")
            if name != "rocAuc" or has_both_classes
        }
    return result


def trusted_ids(corpus: dict[str, Any]) -> tuple[set[str], dict[str, Any]]:
    metadata = corpus["metadata"]
    baseline_count = int(metadata["review_gate"]["baseline_case_count"])
    reviewed = set(metadata["expansion_2026_07_17"]["human_reviewed_ids"])
    baseline = {row["id"] for row in corpus["cases"][:baseline_count]}
    return baseline | reviewed, {
        "baselineRows": len(baseline),
        "reviewedExpansionRows": len(reviewed),
        "policy": "baseline corpus plus owner-accepted human-review sample",
    }


def comparison_block(
    rows: list[dict[str, Any]],
    labels: np.ndarray,
    probabilities: np.ndarray,
    benchmark_path: Path,
) -> dict[str, Any]:
    benchmark = json.loads(benchmark_path.read_text(encoding="utf-8"))
    lexical_by_id = {case["id"]: bool(case["flagged"]) for case in benchmark["cases"]}
    shadow = probabilities >= 0.5
    lexical = np.asarray([lexical_by_id[row["id"]] for row in rows], dtype=bool)
    expected = labels.astype(bool)
    return {
        "lexicalCorrect": int((lexical == expected).sum()),
        "shadowOofCorrect": int((shadow == expected).sum()),
        "bothCorrect": int(((lexical == expected) & (shadow == expected)).sum()),
        "shadowOnlyCorrect": int(((lexical != expected) & (shadow == expected)).sum()),
        "lexicalOnlyCorrect": int(((lexical == expected) & (shadow != expected)).sum()),
        "bothWrong": int(((lexical != expected) & (shadow != expected)).sum()),
        "shadowRescuedLexicalRiskMisses": int(((~lexical) & expected & shadow).sum()),
        "shadowFalsePositivesOnLexicalBenign": int(((~lexical) & (~expected) & shadow).sum()),
    }


def out_of_fold(
    features: np.ndarray,
    labels: np.ndarray,
    groups: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    stratified = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    stratified_probabilities = cross_val_predict(
        new_model(), features, labels, cv=stratified, method="predict_proba"
    )[:, 1]

    # This stricter view keeps scenario families together. It is noisier with
    # only 16 groups, but better exposes whether the model generalizes beyond
    # close variants of a conversation pattern.
    grouped = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
    grouped_probabilities = cross_val_predict(
        new_model(), features, labels, groups=groups, cv=grouped, method="predict_proba"
    )[:, 1]
    return stratified_probabilities, grouped_probabilities


def main() -> None:
    args = parse_args()
    header, all_rows = load_dataset(args.dataset)
    corpus = json.loads(args.corpus.read_text(encoding="utf-8"))
    eligible_ids, selection = trusted_ids(corpus)
    rows = all_rows if args.include_unreviewed else [row for row in all_rows if row["id"] in eligible_ids]
    if not rows:
        raise ValueError("Review gate selected no training rows")
    features = np.asarray([row["values"] for row in rows], dtype=float)
    labels = np.asarray([row["label"] for row in rows], dtype=int)
    groups = np.asarray([row["group"] for row in rows])

    stratified_probabilities, grouped_probabilities = out_of_fold(features, labels, groups)

    final_model = new_model()
    final_model.fit(features, labels)
    coefficients = final_model.coef_[0]
    bias = float(final_model.intercept_[0])

    model_payload = {
        "kind": "logistic_regression",
        "modelId": f"sentinel-linear-sv{int(header['schemaVersion'])}-reviewed-{len(rows)}",
        "schemaVersion": int(header["schemaVersion"]),
        "featureNames": header["names"],
        "coefficients": [float(value) for value in coefficients],
        "bias": bias,
        "threshold": 0.5,
        "trainedRows": len(rows),
        "trainingNote": "Fitted only on review-eligible rows for shadow-only inference; use grouped cross-validation and its intervals for evaluation.",
    }
    report_payload = {
        "dataset": str(args.dataset.relative_to(ROOT)),
        "schemaVersion": int(header["schemaVersion"]),
        "rows": len(rows),
        "availableRows": len(all_rows),
        "selection": {
            **selection,
            "mode": "all_rows_research_only" if args.include_unreviewed else "reviewed_only",
            "excludedUnreviewedRows": 0 if args.include_unreviewed else len(all_rows) - len(rows),
        },
        "classCounts": {
            "benign": int((labels == 0).sum()),
            "risk": int((labels == 1).sum()),
        },
        "threshold": 0.5,
        "crossValidation": {
            "stratified5Fold": metric_block(labels, stratified_probabilities),
            "stratifiedGroup5Fold": metric_block(labels, grouped_probabilities),
        },
        "groupedOofByGroup": {
            group: metric_block(
                labels[groups == group],
                grouped_probabilities[groups == group],
                with_intervals=False,
            )
            for group in sorted(set(groups))
        },
        "lexicalVsGroupedOofShadow": comparison_block(
            rows, labels, grouped_probabilities, args.benchmark
        ),
        "cases": [
            {
                "id": row["id"],
                "group": row["group"],
                "label": row["label"],
                "stratifiedOofProbability": float(stratified_probabilities[index]),
                "groupedOofProbability": float(grouped_probabilities[index]),
            }
            for index, row in enumerate(rows)
        ],
        "limitations": [
            f"Only {len(rows)} review-eligible conversations are used; this is still small for model promotion.",
            f"{len(all_rows) - len(rows)} additional synthetic rows remain excluded from training until review.",
            "Rows come from a curated synthetic benchmark rather than independent production traffic.",
            "Confidence intervals quantify sampling uncertainty over these OOF predictions, not domain shift in real traffic.",
            "The exported full-data model remains shadow-only and must not affect decisions.",
        ],
    }

    args.model_out.parent.mkdir(parents=True, exist_ok=True)
    args.report_out.parent.mkdir(parents=True, exist_ok=True)
    args.model_out.write_text(json.dumps(model_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.report_out.write_text(json.dumps(report_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(json.dumps({
        "selection": report_payload["selection"],
        "crossValidation": report_payload["crossValidation"],
        "lexicalVsGroupedOofShadow": report_payload["lexicalVsGroupedOofShadow"],
    }, indent=2))
    print(f"Exported model to {args.model_out}")


if __name__ == "__main__":
    main()
